### ISSUE TITLE
Create Workout routine and logging

### ISSUE THREAD

**Issue by thomasweigert91** [thomasweigert91/capstoneproject#6]
### Value Proposition

As a user, i would like to have the possibility to build my own training routine and fill it with important training data during the workout

### Description

![image](https://user-images.githubusercontent.com/114309234/206216774-4fa210b8-40a8-4370-b195-f2e6c3e39eb1.png)

![image](https://user-images.githubusercontent.com/114309234/206216857-18206b59-635e-485b-a0c3-927228c148df.png)

![image](https://user-images.githubusercontent.com/114309234/206216959-b0141ae7-040a-4660-9cb8-6cd95ee83d58.png)

### Acceptance Criteria

The routines tab takes the user to the menu where existing routines are displayed. the new routine button takes the user to a new page. there, the add exercise button allows the user to add exercises to their plan. These are saved on the create routine page. the routine is created via save and can then be called up. in addition, the user has the option of adjusting and saving the number of sets and the weights. once the routine has been completed, it is displayed on the start page.

### Tasks

(for developers team)

- [ ]Create routine component
- [ ] create add exercise button
- [ ] create all components for the intra workout screen
- [ ] add functionality that allows exercises to be added to the routine
- [ ] add functionality to add and delete sets
- [ ] add functionality to edit weights and reps
- [ ] add functionality to save the routine

### Sizing/Complexity

**L**
